// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// readsas
Rcpp::List readsas(const char * filePath, const bool debug, const int64_t kk);
RcppExport SEXP _readsas_readsas(SEXP filePathSEXP, SEXP debugSEXP, SEXP kkSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const char * >::type filePath(filePathSEXP);
    Rcpp::traits::input_parameter< const bool >::type debug(debugSEXP);
    Rcpp::traits::input_parameter< const int64_t >::type kk(kkSEXP);
    rcpp_result_gen = Rcpp::wrap(readsas(filePath, debug, kk));
    return rcpp_result_gen;
END_RCPP
}
// writesas
void writesas(const char * filePath, Rcpp::DataFrame dat, uint8_t compress, bool debug, bool bit32);
RcppExport SEXP _readsas_writesas(SEXP filePathSEXP, SEXP datSEXP, SEXP compressSEXP, SEXP debugSEXP, SEXP bit32SEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const char * >::type filePath(filePathSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type dat(datSEXP);
    Rcpp::traits::input_parameter< uint8_t >::type compress(compressSEXP);
    Rcpp::traits::input_parameter< bool >::type debug(debugSEXP);
    Rcpp::traits::input_parameter< bool >::type bit32(bit32SEXP);
    writesas(filePath, dat, compress, debug, bit32);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_readsas_readsas", (DL_FUNC) &_readsas_readsas, 3},
    {"_readsas_writesas", (DL_FUNC) &_readsas_writesas, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_readsas(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
