# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Reads SAS data files
#'
#' @param filePath The full systempath to the sas7bdat file you want to import.
#' @param debug print debug information
#' @param selectrows_ integer vector of selected rows
#' @param selectcols_ character vector of selected rows
#' @import Rcpp
#' @export
readsas <- function(filePath, debug, selectrows_, selectcols_) {
    .Call(`_readsas_readsas`, filePath, debug, selectrows_, selectcols_)
}

