# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Reads SAS data files
#'
#' @param filePath The full systempath to the sas7bdat file you want to import.
#' @param debug print debug information
#' @param selectrows_ integer vector of selected rows
#' @param selectcols_ character vector of selected rows
#' @param empty_to_na logical convert '' to NA_character_
#' @param tempstr filepath used for temp output when uncompressing
#' @import Rcpp
#' @keywords internal
#' @noRd
readsas <- function(filePath, debug, selectrows_, selectcols_, empty_to_na, tempstr) {
    .Call(`_readsas_readsas`, filePath, debug, selectrows_, selectcols_, empty_to_na, tempstr)
}

#' Writes the binary SAS file
#'
#' @param filePath The full systempath to the sas7bdat file you want to export.
#' @param dat an R-Object of class data.frame.
#' @param compress the file
#' @param debug print debug information
#' @param bit32 write smaller 32 bit file
#' @param headersize,pagesize size parameters 512 / 1024 times x
#' @param dateval timestamp
#' @keywords internal
#' @noRd
writesas <- function(filePath, dat, compress, debug, bit32, headersize, pagesize, dateval) {
    invisible(.Call(`_readsas_writesas`, filePath, dat, compress, debug, bit32, headersize, pagesize, dateval))
}

